change class PropertiesFileGetter
ivm23/EPAM_HomeWork pull request #10
Opened 2018-04-01 18:59 UTC by ivm23

2018-04-01 19:01 UTC, ivm23 commented on hwSixTask/src/main/java/PropertiesFileGetter.java
> +public class PropertiesFileGetter {
Был такой комментарий
"По условию задачи,чтение файла должно происходить только один раз. А у Вас метод getProperties - public, и каждый раз при его вызове будет происходить чтение. Подумайте, пожалуйста, как помнять структуру файла, чтобы можно было прочитать всего один раз, при первом обращении к папке, а потом просто брать из неё значения."

2018-04-05 17:29 UTC, AnnaS91 requested changes

2018-04-05 17:29 UTC, AnnaS91 commented on hwSixTask/src/main/java/PropertiesFileGetter.java
> +    public static Map getPropertiesMap() {
1)лучше всё-таки возвращать пользователю не целый Map, а значение по ключу
2) Map - дженерик, поэтому чтобы не было проблем с приведением типов лучше всегда указывать полностью что он возвращает <Pair<...>, ...>

2018-04-08 12:32 UTC, AnnaS91 approved these changes

2018-04-08 13:09 UTC, merged